In [87]:
import pandas as pd
df = pd.read_csv("all_fights.csv")

In [88]:
df.duplicated().sum()

np.int64(0)

In [89]:
#Convert fight_date to datetime and sequence it chronologically
df["fight_date"] = pd.to_datetime(df["fight_date"])
df = df.sort_values('fight_date').reset_index(drop=True)

In [90]:
#Check null values
df.isnull().sum().sort_values(ascending=False)

red_fighter                 0
blue_current_lose_streak    0
blue_longest_win_streak     0
blue_losses                 0
blue_total_rounds_fought    0
blue_total_title_bouts      0
blue_wins_by_ko             0
blue_wins_by_submission     0
blue_wins                   0
blue_stance                 0
blue_height_cms             0
blue_reach_cms              0
red_current_lose_streak     0
red_current_win_streak      0
red_longest_win_streak      0
red_losses                  0
red_total_rounds_fought     0
red_total_title_bouts       0
red_wins_by_ko              0
red_wins_by_submission      0
red_wins                    0
red_stance                  0
red_height_cms              0
red_reach_cms               0
red_age                     0
blue_age                    0
b_match_wc_rank             0
blue_current_win_streak     0
number_of_rounds            0
blue_fighter                0
gender                      0
red_odds                    0
blue_odds                   0
red_winner                  0
red_return                  0
blue_return                 0
odds_diff                   0
age_diff                    0
reach_diff                  0
height_diff                 0
wins_diff                   0
losses_diff                 0
rounds_diff                 0
title_bout_diff             0
ko_diff                     0
submission_diff             0
win_streak_diff             0
lose_streak_diff            0
longest_win_streak_diff     0
sig_str_diff                0
sub_att_diff                0
td_diff                     0
rank_diff                   0
fight_date                  0
title_bout                  0
weight_class                0
r_match_wc_rank             0
dtype: int64

In [91]:
#Change categorical data into binary values
df['red_stance'] = df['red_stance'].map({'Southpaw': 1, 'Orthodox': 0})
df['blue_stance'] = df['blue_stance'].map({'Southpaw': 1, 'Orthodox': 0})
df['gender'] = df['gender'].map({'MALE': 1, 'FEMALE': 0})

In [92]:
df['red_stance'] = df['red_stance'].fillna(2)
df['blue_stance'] = df['blue_stance'].fillna(2)
df['red_stance'].isna().sum()

np.int64(0)

In [93]:
df['weight_class'].isna().sum()

np.int64(0)

In [94]:
#weight_class has too many categories to change into binary manually. Use OneHotEncoder.
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_array = encoder.fit_transform(df[['weight_class']])
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(['weight_class']),
    index=df.index
)
encoded_df.head()

,weight_class_Bantamweight,weight_class_Catch Weight,weight_class_Featherweight,weight_class_Flyweight,weight_class_Heavyweight,weight_class_Light Heavyweight,weight_class_Lightweight,weight_class_Middleweight,weight_class_Welterweight,weight_class_Women's Bantamweight,weight_class_Women's Featherweight,weight_class_Women's Flyweight,weight_class_Women's Strawweight
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
encoded_df.isna().sum()

weight_class_Bantamweight             0
weight_class_Catch Weight             0
weight_class_Featherweight            0
weight_class_Flyweight                0
weight_class_Heavyweight              0
weight_class_Light Heavyweight        0
weight_class_Lightweight              0
weight_class_Middleweight             0
weight_class_Welterweight             0
weight_class_Women's Bantamweight     0
weight_class_Women's Featherweight    0
weight_class_Women's Flyweight        0
weight_class_Women's Strawweight      0
dtype: int64

In [96]:
df1 = df.copy()
df1.head()

,red_fighter,blue_fighter,red_odds,blue_odds,red_winner,red_return,blue_return,odds_diff,age_diff,reach_diff,...,red_wins_by_ko,red_wins_by_submission,red_wins,red_stance,red_height_cms,red_reach_cms,red_age,blue_age,b_match_wc_rank,r_match_wc_rank
0,Eric Schafer,Jason Brilz,140,-160,f,0.0000,1.625,300,-2,10.16,...,1,2,3,0.0,190.50,190.50,32,34,20,20
1,Mike Pierce,Julio Paulino,-420,335,t,1.2381,0.000,-755,-5,-7.62,...,0,0,1,0.0,172.72,177.80,29,34,20,20
2,Brendan Schaub,Chase Gormley,-260,220,t,1.3846,0.000,-480,0,2.12,...,0,0,0,0.0,193.04,198.12,27,27,20,20
3,John Howard,Daniel Roberts,-210,175,t,1.4762,0.000,-385,-2,-7.62,...,1,0,3,0.0,170.18,180.34,27,29,20,20
4,Duane Ludwig,Darren Elkins,-155,135,f,0.0000,2.350,-290,6,-2.54,...,1,0,2,0.0,177.80,177.80,31,25,20,20

In [97]:
#Join encoded df with main df
df2 = df1.join(encoded_df, how='inner')
df2.isna().sum()

red_fighter                           0
blue_fighter                          0
red_odds                              0
blue_odds                             0
red_winner                            0
                                     ..
weight_class_Welterweight             0
weight_class_Women's Bantamweight     0
weight_class_Women's Featherweight    0
weight_class_Women's Flyweight        0
weight_class_Women's Strawweight      0
Length: 70, dtype: int64

In [98]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7265 entries, 0 to 7264
Data columns (total 70 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   red_fighter                         7265 non-null   str
 1   blue_fighter                        7265 non-null   str
 2   red_odds                            7265 non-null   int64
 3   blue_odds                           7265 non-null   int64
 4   red_winner                          7265 non-null   str
 5   red_return                          7265 non-null   float64
 6   blue_return                         7265 non-null   float64
 7   odds_diff                           7265 non-null   int64
 8   age_diff                            7265 non-null   int64
 9   reach_diff                          7265 non-null   float64
 10  height_diff                         7265 non-null   float64
 11  wins_diff                           7265 non-null   int64
 12  losses_diff                         7265 non-null   int64
 13  rounds_diff                         7265 non-null   int64
 14  title_bout_diff                     7265 non-null   int64
 15  ko_diff                             7265 non-null   int64
 16  submission_diff                     7265 non-null   int64
 17  win_streak_diff                     7265 non-null   int64
 18  lose_streak_diff                    7265 non-null   int64
 19  longest_win_streak_diff             7265 non-null   int64
 20  sig_str_diff                        7265 non-null   float64
 21  sub_att_diff                        7265 non-null   float64
 22  td_diff                             7265 non-null   float64
 23  rank_diff                           7265 non-null   int64
 24  fight_date                          7265 non-null   datetime64[us]
 25  title_bout                          7265 non-null   str
 26  weight_class                        7265 non-null   str
 27  gender                              7265 non-null   int64
 28  number_of_rounds                    7265 non-null   int64
 29  blue_current_lose_streak            7265 non-null   int64
 30  blue_current_win_streak             7265 non-null   int64
 31  blue_longest_win_streak             7265 non-null   int64
 32  blue_losses                         7265 non-null   int64
 33  blue_total_rounds_fought            7265 non-null   int64
 34  blue_total_title_bouts              7265 non-null   int64
 35  blue_wins_by_ko                     7265 non-null   int64
 36  blue_wins_by_submission             7265 non-null   int64
 37  blue_wins                           7265 non-null   int64
 38  blue_stance                         7265 non-null   float64
 39  blue_height_cms                     7265 non-null   float64
 40  blue_reach_cms                      7265 non-null   float64
 41  red_current_lose_streak             7265 non-null   int64
 42  red_current_win_streak              7265 non-null   int64
 43  red_longest_win_streak              7265 non-null   int64
 44  red_losses                          7265 non-null   int64
 45  red_total_rounds_fought             7265 non-null   int64
 46  red_total_title_bouts               7265 non-null   int64
 47  red_wins_by_ko                      7265 non-null   int64
 48  red_wins_by_submission              7265 non-null   int64
 49  red_wins                            7265 non-null   int64
 50  red_stance                          7265 non-null   float64
 51  red_height_cms                      7265 non-null   float64
 52  red_reach_cms                       7265 non-null   float64
 53  red_age                             7265 non-null   int64
 54  blue_age                            7265 non-null   int64
 55  b_match_wc_rank                     7265 non-null   int64
 56  r_match_wc_rank                     7265 non-null   int64
 57  weight_class_Bantamweight           7265 non-null   float64
 58  weight_class_Catch Weight           7265 non-null   float64
 59  weight_class_Featherweight          7265 non-null   float64
 60  weight_class_Flyweight              7265 non-null   float64
 61  weight_class_Heavyweight            7265 non-null   float64
 62  weight_class_Light Heavyweight      7265 non-null   float64
 63  weight_class_Lightweight            7265 non-null   float64
 64  weight_class_Middleweight           7265 non-null   float64
 65  weight_class_Welterweight           7265 non-null   float64
 66  weight_class_Women's Bantamweight   7265 non-null   float64
 67  weight_class_Women's Featherweight  7265 non-null   float64
 68  weight_class_Women's Flyweight      7265 non-null   float64
 69  weight_class_Women's Strawweight    7265 non-null   float64
dtypes: datetime64[us](1), float64(26), int64(38), str(5)
memory usage: 3.7 MB

In [99]:
df2['title_bout'] = df2['title_bout'].map({'t': 1, 'f': 0})
df2['red_winner'] = df2['red_winner'].map({'t': 1, 'f': 0})
df2.head()

,red_fighter,blue_fighter,red_odds,blue_odds,red_winner,red_return,blue_return,odds_diff,age_diff,reach_diff,...,weight_class_Flyweight,weight_class_Heavyweight,weight_class_Light Heavyweight,weight_class_Lightweight,weight_class_Middleweight,weight_class_Welterweight,weight_class_Women's Bantamweight,weight_class_Women's Featherweight,weight_class_Women's Flyweight,weight_class_Women's Strawweight
0,Eric Schafer,Jason Brilz,140,-160,0,0.0000,1.625,300,-2,10.16,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Mike Pierce,Julio Paulino,-420,335,1,1.2381,0.000,-755,-5,-7.62,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,Brendan Schaub,Chase Gormley,-260,220,1,1.3846,0.000,-480,0,2.12,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,John Howard,Daniel Roberts,-210,175,1,1.4762,0.000,-385,-2,-7.62,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Duane Ludwig,Darren Elkins,-155,135,0,0.0000,2.350,-290,6,-2.54,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [100]:
df2 = df2.drop(columns=['red_return', 'blue_return'])

In [101]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7265 entries, 0 to 7264
Data columns (total 68 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   red_fighter                         7265 non-null   str
 1   blue_fighter                        7265 non-null   str
 2   red_odds                            7265 non-null   int64
 3   blue_odds                           7265 non-null   int64
 4   red_winner                          7265 non-null   int64
 5   odds_diff                           7265 non-null   int64
 6   age_diff                            7265 non-null   int64
 7   reach_diff                          7265 non-null   float64
 8   height_diff                         7265 non-null   float64
 9   wins_diff                           7265 non-null   int64
 10  losses_diff                         7265 non-null   int64
 11  rounds_diff                         7265 non-null   int64
 12  title_bout_diff                     7265 non-null   int64
 13  ko_diff                             7265 non-null   int64
 14  submission_diff                     7265 non-null   int64
 15  win_streak_diff                     7265 non-null   int64
 16  lose_streak_diff                    7265 non-null   int64
 17  longest_win_streak_diff             7265 non-null   int64
 18  sig_str_diff                        7265 non-null   float64
 19  sub_att_diff                        7265 non-null   float64
 20  td_diff                             7265 non-null   float64
 21  rank_diff                           7265 non-null   int64
 22  fight_date                          7265 non-null   datetime64[us]
 23  title_bout                          7265 non-null   int64
 24  weight_class                        7265 non-null   str
 25  gender                              7265 non-null   int64
 26  number_of_rounds                    7265 non-null   int64
 27  blue_current_lose_streak            7265 non-null   int64
 28  blue_current_win_streak             7265 non-null   int64
 29  blue_longest_win_streak             7265 non-null   int64
 30  blue_losses                         7265 non-null   int64
 31  blue_total_rounds_fought            7265 non-null   int64
 32  blue_total_title_bouts              7265 non-null   int64
 33  blue_wins_by_ko                     7265 non-null   int64
 34  blue_wins_by_submission             7265 non-null   int64
 35  blue_wins                           7265 non-null   int64
 36  blue_stance                         7265 non-null   float64
 37  blue_height_cms                     7265 non-null   float64
 38  blue_reach_cms                      7265 non-null   float64
 39  red_current_lose_streak             7265 non-null   int64
 40  red_current_win_streak              7265 non-null   int64
 41  red_longest_win_streak              7265 non-null   int64
 42  red_losses                          7265 non-null   int64
 43  red_total_rounds_fought             7265 non-null   int64
 44  red_total_title_bouts               7265 non-null   int64
 45  red_wins_by_ko                      7265 non-null   int64
 46  red_wins_by_submission              7265 non-null   int64
 47  red_wins                            7265 non-null   int64
 48  red_stance                          7265 non-null   float64
 49  red_height_cms                      7265 non-null   float64
 50  red_reach_cms                       7265 non-null   float64
 51  red_age                             7265 non-null   int64
 52  blue_age                            7265 non-null   int64
 53  b_match_wc_rank                     7265 non-null   int64
 54  r_match_wc_rank                     7265 non-null   int64
 55  weight_class_Bantamweight           7265 non-null   float64
 56  weight_class_Catch Weight           7265 non-null   float64
 57  weight_class_Featherweight          7265 non-null   float64
 58  weight_class_Flyweight              7265 non-null   float64
 59  weight_class_Heavyweight            7265 non-null   float64
 60  weight_class_Light Heavyweight      7265 non-null   float64
 61  weight_class_Lightweight            7265 non-null   float64
 62  weight_class_Middleweight           7265 non-null   float64
 63  weight_class_Welterweight           7265 non-null   float64
 64  weight_class_Women's Bantamweight   7265 non-null   float64
 65  weight_class_Women's Featherweight  7265 non-null   float64
 66  weight_class_Women's Flyweight      7265 non-null   float64
 67  weight_class_Women's Strawweight    7265 non-null   float64
dtypes: datetime64[us](1), float64(24), int64(40), str(3)
memory usage: 3.7 MB

In [102]:
#Turn American odds into probability
#Start Feature Engineering
def american_to_prob(odds):
    if odds < 0:
        return abs(odds)/(abs(odds) + 100)
    else:
        return 100/(abs(odds) + 100)

In [103]:
df2["red_implied_prob"] = df2["red_odds"].apply(american_to_prob)

df2["blue_implied_prob"] = df2["blue_odds"].apply(american_to_prob)

In [104]:
df2['prob_diff'] = (df2['red_implied_prob'] - df2['blue_implied_prob'])

In [105]:
df2.head()

,red_fighter,blue_fighter,red_odds,blue_odds,red_winner,odds_diff,age_diff,reach_diff,height_diff,wins_diff,...,weight_class_Lightweight,weight_class_Middleweight,weight_class_Welterweight,weight_class_Women's Bantamweight,weight_class_Women's Featherweight,weight_class_Women's Flyweight,weight_class_Women's Strawweight,red_implied_prob,blue_implied_prob,prob_diff
0,Eric Schafer,Jason Brilz,140,-160,0,300,-2,10.16,10.16,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.416667,0.615385,-0.198718
1,Mike Pierce,Julio Paulino,-420,335,1,-755,-5,-7.62,-10.16,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.807692,0.229885,0.577807
2,Brendan Schaub,Chase Gormley,-260,220,1,-480,0,2.12,2.54,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.722222,0.312500,0.409722
3,John Howard,Daniel Roberts,-210,175,1,-385,-2,-7.62,-7.62,3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.677419,0.363636,0.313783
4,Duane Ludwig,Darren Elkins,-155,135,0,-290,6,-2.54,0.00,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.607843,0.425532,0.182311

In [106]:
#Win Percentage
df2['red_win_pct'] = df2['red_wins']/(df2['red_wins']+df2['red_losses'])
df2['red_win_pct'].info()

<class 'pandas.Series'>
RangeIndex: 7265 entries, 0 to 7264
Series name: red_win_pct
Non-Null Count  Dtype
--------------  -----
6786 non-null   float64
dtypes: float64(1)
memory usage: 56.8 KB

In [107]:
df2['blue_win_pct'] = df2['blue_wins']/(df2['blue_wins']+ df2['blue_losses'])
df2['win_pct_diff'] = df2['red_win_pct'] - df2['blue_win_pct']

In [108]:
#KO Rate
df2['red_ko_rate'] = df2['red_wins_by_ko']/df2['red_wins']
df2['blue_ko_rate'] = df2['blue_wins_by_ko']/df2['blue_wins']

In [109]:
#Submission Rate
df2['red_sub_rate'] = df2['red_wins_by_submission']/df2['red_wins']
df2['blue_sub_rate'] = df2['blue_wins_by_submission']/df2['blue_wins']

In [110]:
#Finish Rate
df2['red_finish_rate'] = (df2['red_wins_by_ko']+ df2['red_wins_by_submission'])/df2['red_wins']
df2['blue_finish_rate'] = (df2['blue_wins_by_ko'] + df2['blue_wins_by_submission'])/df2['blue_wins']

In [111]:
#Total Fights
df2['red_experience'] = df2['red_wins'] + df2['red_losses']
df2['blue_experience'] = df2['blue_wins'] + df2['blue_losses']

In [112]:
#Average Round per Fight
df2['red_round_per_fight'] = df2['red_total_rounds_fought']/df2['red_experience']
df2['blue_round_per_fight'] = df2['blue_total_rounds_fought']/df2['blue_experience']

In [113]:
#Reach Per Height
df2['red_reach_per_height'] = df2['red_reach_cms']/df2['red_height_cms']
df2['blue_reach_per_height'] = df2['blue_reach_cms']/df2['blue_height_cms']

In [114]:
#Number of days since the fighter fought last
last_fight_date = {}
df2['red_days_since_last'] = None
df2['blue_days_since_last'] = None

for index, row in df2.iterrows():

    red = row["red_fighter"]
    blue = row["blue_fighter"]

    fight_date = row["fight_date"]

    # Red fighter
    if red in last_fight_date:
        days = (fight_date - last_fight_date[red]).days
        df2.loc[index, "red_days_since_last"] = days
    else:
        df2.loc[index, "red_days_since_last"] = None

    # Blue fighter
    if blue in last_fight_date:
        days = (fight_date - last_fight_date[blue]).days
        df2.loc[index, "blue_days_since_last"] = days
    else:
        df2.loc[index, "blue_days_since_last"] = None

    
    last_fight_date[red] = fight_date
    last_fight_date[blue] = fight_date

In [116]:
df2.tail()

,red_fighter,blue_fighter,red_odds,blue_odds,red_winner,odds_diff,age_diff,reach_diff,height_diff,wins_diff,...,red_finish_rate,blue_finish_rate,red_experience,blue_experience,red_round_per_fight,blue_round_per_fight,red_reach_per_height,blue_reach_per_height,red_days_since_last,blue_days_since_last
7260,Tuco Tokkos,Ivan Erslan,154,-200,0,354,1,10.16,5.08,1,...,1.000000,NaN,4,3,1.750000,2.333333,1.000000,0.972973,308,231
7261,Arnold Allen,Melquizael Costa,-180,140,1,-320,3,-2.54,-5.08,4,...,0.363636,0.571429,14,9,2.928571,2.111111,1.029412,1.014286,112,84
7262,Alice Ardelean,Polyana Viana,-205,158,1,-363,1,-12.70,-5.08,-2,...,0.000000,1.000000,4,11,3.000000,1.818182,0.984127,1.030769,196,385
7263,Daniel Barez,Luis Gurule,-113,-113,0,0,5,5.08,2.54,0,...,0.000000,0.000000,4,4,2.500000,2.750000,1.000000,0.984615,427,84
7264,Malcolm Wellmaker,Juan Diaz,-265,200,0,-465,4,5.08,5.08,2,...,1.000000,1.000000,4,1,1.500000,2.000000,1.014286,1.014706,182,None

In [117]:
#Debut Fighters
df2["red_debut"] = df2["red_days_since_last"].isna().astype(int)
df2["blue_debut"] = df2["blue_days_since_last"].isna().astype(int)

In [118]:
df2["activity_diff"] = (
    df2["red_days_since_last"] -
    df2["blue_days_since_last"]
)

In [119]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7265 entries, 0 to 7264
Data columns (total 91 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   red_fighter                         7265 non-null   str
 1   blue_fighter                        7265 non-null   str
 2   red_odds                            7265 non-null   int64
 3   blue_odds                           7265 non-null   int64
 4   red_winner                          7265 non-null   int64
 5   odds_diff                           7265 non-null   int64
 6   age_diff                            7265 non-null   int64
 7   reach_diff                          7265 non-null   float64
 8   height_diff                         7265 non-null   float64
 9   wins_diff                           7265 non-null   int64
 10  losses_diff                         7265 non-null   int64
 11  rounds_diff                         7265 non-null   int64
 12  title_bout_diff                     7265 non-null   int64
 13  ko_diff                             7265 non-null   int64
 14  submission_diff                     7265 non-null   int64
 15  win_streak_diff                     7265 non-null   int64
 16  lose_streak_diff                    7265 non-null   int64
 17  longest_win_streak_diff             7265 non-null   int64
 18  sig_str_diff                        7265 non-null   float64
 19  sub_att_diff                        7265 non-null   float64
 20  td_diff                             7265 non-null   float64
 21  rank_diff                           7265 non-null   int64
 22  fight_date                          7265 non-null   datetime64[us]
 23  title_bout                          7265 non-null   int64
 24  weight_class                        7265 non-null   str
 25  gender                              7265 non-null   int64
 26  number_of_rounds                    7265 non-null   int64
 27  blue_current_lose_streak            7265 non-null   int64
 28  blue_current_win_streak             7265 non-null   int64
 29  blue_longest_win_streak             7265 non-null   int64
 30  blue_losses                         7265 non-null   int64
 31  blue_total_rounds_fought            7265 non-null   int64
 32  blue_total_title_bouts              7265 non-null   int64
 33  blue_wins_by_ko                     7265 non-null   int64
 34  blue_wins_by_submission             7265 non-null   int64
 35  blue_wins                           7265 non-null   int64
 36  blue_stance                         7265 non-null   float64
 37  blue_height_cms                     7265 non-null   float64
 38  blue_reach_cms                      7265 non-null   float64
 39  red_current_lose_streak             7265 non-null   int64
 40  red_current_win_streak              7265 non-null   int64
 41  red_longest_win_streak              7265 non-null   int64
 42  red_losses                          7265 non-null   int64
 43  red_total_rounds_fought             7265 non-null   int64
 44  red_total_title_bouts               7265 non-null   int64
 45  red_wins_by_ko                      7265 non-null   int64
 46  red_wins_by_submission              7265 non-null   int64
 47  red_wins                            7265 non-null   int64
 48  red_stance                          7265 non-null   float64
 49  red_height_cms                      7265 non-null   float64
 50  red_reach_cms                       7265 non-null   float64
 51  red_age                             7265 non-null   int64
 52  blue_age                            7265 non-null   int64
 53  b_match_wc_rank                     7265 non-null   int64
 54  r_match_wc_rank                     7265 non-null   int64
 55  weight_class_Bantamweight           7265 non-null   float64
 56  weight_class_Catch Weight           7265 non-null   float64
 57  weight_class_Featherweight          7265 non-null   float64
 58  weight_class_Flyweight              7265 non-null   float64
 59  weight_class_Heavyweight            7265 non-null   float64
 60  weight_class_Light Heavyweight      7265 non-null   float64
 61  weight_class_Lightweight            7265 non-null   float64
 62  weight_class_Middleweight           7265 non-null   float64
 63  weight_class_Welterweight           7265 non-null   float64
 64  weight_class_Women's Bantamweight   7265 non-null   float64
 65  weight_class_Women's Featherweight  7265 non-null   float64
 66  weight_class_Women's Flyweight      7265 non-null   float64
 67  weight_class_Women's Strawweight    7265 non-null   float64
 68  red_implied_prob                    7265 non-null   float64
 69  blue_implied_prob                   7265 non-null   float64
 70  prob_diff                           7265 non-null   float64
 71  red_win_pct                         6786 non-null   float64
 72  blue_win_pct                        6111 non-null   float64
 73  win_pct_diff                        5919 non-null   float64
 74  red_ko_rate                         6333 non-null   float64
 75  blue_ko_rate                        5376 non-null   float64
 76  red_sub_rate                        6333 non-null   float64
 77  blue_sub_rate                       5376 non-null   float64
 78  red_finish_rate                     6334 non-null   float64
 79  blue_finish_rate                    5376 non-null   float64
 80  red_experience                      7265 non-null   int64
 81  blue_experience                     7265 non-null   int64
 82  red_round_per_fight                 6791 non-null   float64
 83  blue_round_per_fight                6119 non-null   float64
 84  red_reach_per_height                7265 non-null   float64
 85  blue_reach_per_height               7265 non-null   float64
 86  red_days_since_last                 6495 non-null   object
 87  blue_days_since_last                5778 non-null   object
 88  red_debut                           7265 non-null   int32
 89  blue_debut                          7265 non-null   int32
 90  activity_diff                       5452 non-null   object
dtypes: datetime64[us](1), float64(40), int32(2), int64(42), object(3), str(3)
memory usage: 4.8+ MB

In [120]:
#
df2 = df2.drop(columns=['red_fighter', 'blue_fighter', 'red_wins', 'red_losses', 'blue_wins', 'blue_losses', 'red_wins_by_ko',
                       'blue_wins_by_ko', 'weight_class', 'fight_date', 'red_wins_by_submission', 'blue_wins_by_submission'])

In [122]:
df2['red_days_since_last'] = pd.to_numeric(df2['red_days_since_last'], errors='coerce')
df2['blue_days_since_last'] = pd.to_numeric(df2['blue_days_since_last'], errors='coerce')
df2['activity_diff'] = pd.to_numeric(df2['activity_diff'], errors='coerce')
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7265 entries, 0 to 7264
Data columns (total 79 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   red_odds                            7265 non-null   int64
 1   blue_odds                           7265 non-null   int64
 2   red_winner                          7265 non-null   int64
 3   odds_diff                           7265 non-null   int64
 4   age_diff                            7265 non-null   int64
 5   reach_diff                          7265 non-null   float64
 6   height_diff                         7265 non-null   float64
 7   wins_diff                           7265 non-null   int64
 8   losses_diff                         7265 non-null   int64
 9   rounds_diff                         7265 non-null   int64
 10  title_bout_diff                     7265 non-null   int64
 11  ko_diff                             7265 non-null   int64
 12  submission_diff                     7265 non-null   int64
 13  win_streak_diff                     7265 non-null   int64
 14  lose_streak_diff                    7265 non-null   int64
 15  longest_win_streak_diff             7265 non-null   int64
 16  sig_str_diff                        7265 non-null   float64
 17  sub_att_diff                        7265 non-null   float64
 18  td_diff                             7265 non-null   float64
 19  rank_diff                           7265 non-null   int64
 20  title_bout                          7265 non-null   int64
 21  gender                              7265 non-null   int64
 22  number_of_rounds                    7265 non-null   int64
 23  blue_current_lose_streak            7265 non-null   int64
 24  blue_current_win_streak             7265 non-null   int64
 25  blue_longest_win_streak             7265 non-null   int64
 26  blue_total_rounds_fought            7265 non-null   int64
 27  blue_total_title_bouts              7265 non-null   int64
 28  blue_stance                         7265 non-null   float64
 29  blue_height_cms                     7265 non-null   float64
 30  blue_reach_cms                      7265 non-null   float64
 31  red_current_lose_streak             7265 non-null   int64
 32  red_current_win_streak              7265 non-null   int64
 33  red_longest_win_streak              7265 non-null   int64
 34  red_total_rounds_fought             7265 non-null   int64
 35  red_total_title_bouts               7265 non-null   int64
 36  red_stance                          7265 non-null   float64
 37  red_height_cms                      7265 non-null   float64
 38  red_reach_cms                       7265 non-null   float64
 39  red_age                             7265 non-null   int64
 40  blue_age                            7265 non-null   int64
 41  b_match_wc_rank                     7265 non-null   int64
 42  r_match_wc_rank                     7265 non-null   int64
 43  weight_class_Bantamweight           7265 non-null   float64
 44  weight_class_Catch Weight           7265 non-null   float64
 45  weight_class_Featherweight          7265 non-null   float64
 46  weight_class_Flyweight              7265 non-null   float64
 47  weight_class_Heavyweight            7265 non-null   float64
 48  weight_class_Light Heavyweight      7265 non-null   float64
 49  weight_class_Lightweight            7265 non-null   float64
 50  weight_class_Middleweight           7265 non-null   float64
 51  weight_class_Welterweight           7265 non-null   float64
 52  weight_class_Women's Bantamweight   7265 non-null   float64
 53  weight_class_Women's Featherweight  7265 non-null   float64
 54  weight_class_Women's Flyweight      7265 non-null   float64
 55  weight_class_Women's Strawweight    7265 non-null   float64
 56  red_implied_prob                    7265 non-null   float64
 57  blue_implied_prob                   7265 non-null   float64
 58  prob_diff                           7265 non-null   float64
 59  red_win_pct                         6786 non-null   float64
 60  blue_win_pct                        6111 non-null   float64
 61  win_pct_diff                        5919 non-null   float64
 62  red_ko_rate                         6333 non-null   float64
 63  blue_ko_rate                        5376 non-null   float64
 64  red_sub_rate                        6333 non-null   float64
 65  blue_sub_rate                       5376 non-null   float64
 66  red_finish_rate                     6334 non-null   float64
 67  blue_finish_rate                    5376 non-null   float64
 68  red_experience                      7265 non-null   int64
 69  blue_experience                     7265 non-null   int64
 70  red_round_per_fight                 6791 non-null   float64
 71  blue_round_per_fight                6119 non-null   float64
 72  red_reach_per_height                7265 non-null   float64
 73  blue_reach_per_height               7265 non-null   float64
 74  red_days_since_last                 6495 non-null   float64
 75  blue_days_since_last                5778 non-null   float64
 76  red_debut                           7265 non-null   int32
 77  blue_debut                          7265 non-null   int32
 78  activity_diff                       5452 non-null   float64
dtypes: float64(43), int32(2), int64(34)
memory usage: 4.3 MB

In [123]:
df2.to_csv(
    "processed_ufc_fights.csv",
    index=False
)